### PR TITLE
First version of AUP module

### PR DESCRIPTION
**Pull request by lionick**
[RCIAM-428](https://jira.argo.grnet.gr/browse/RCIAM-428) Terms & Conditions(AUP) Handle

### CODE REVIEW

**Review by NicolasLiampotis — CHANGES_REQUESTED** [review]
* Use state['rciamAttributes']['registryUserId']
* Improve documentation
  * Add default values to any option that has a default
  * Indicate whether option is required or optional

**Comment by lionick** [comment]
> * Use state['rciamAttributes']['registryUserId']
> * Improve documentation
>   
>   * Add default values to any option that has a default
>   * Indicate whether option is required or optional

No default values.
I have made the changes for required and optional.

**Review by NicolasLiampotis — CHANGES_REQUESTED** [review]
Rename `Client` class to `UpdateAUP`

**Review by NicolasLiampotis — APPROVED** [review]
LGTM

**Pull request merged**
